---
- name: Install Apache
  hosts: node2
  become: true


  tasks:
    - name: Ensure apache is installed
      yum:
        name: httpd
        state: latest

    - name: Ensure apache is runing and start at root
      service:
        name: httpd
        state: started
        enable: true 

