---
- name: Apache insallation
  hosts: nodes
  #remote_user: vagrant
  become: yes


  tasks:
        - name: Apache uninstallation
          apt:
           name: apache2
           autoremove: yes
           state: absent
          when: ansible_distribution == 'Ubunu'
                #  enabled: yes
                #
        - name: httpd uninstall
          yum:
            name: httpd
            state: absent
          when: ansible_distribution == 'CentOS'
