- name: Install httpd and firewalld in RHEL
  yum:
    name: 
      - '{{ web_pkg }}'
      - '{{ firewalld_pkg }}'
    state: latest
  when: ansible_distribution == "RedHat"

- name: Install apace2 and firewalld in Ubuntu
  apt:
    name:
      - '{{ web_pkg2 }}'
      - '{{ firewalld_pkg }}'
    state: latest
  when: ansible_distribution == "Ubuntu"
  
- name: firewalld permit http service
  firewalld:
    service: http
    permanent: true    #Should this configuration be in the running firewalld configuration or persist across reboots.
    state: enabled
    immediate: no     #Should this configuration be applied immediately, if set as permanent.
  when: ansible_distribution == "RedHat" and "Ubuntu"


  
  notify:
    - restart httpd
    - restart firewalld
- name: Test html page is installed
  #copy:
  template:
          #content: "Welcome to the ansible demo....!\n"
    src: files/index.html.j2
    dest: /var/www/html/index.html

- name: Restart everything
  command: echo "this task will restart the web services"
  notify: "restart web services"
