- name: restart firewalld
  service: 
    name: firewalld
    enabled: true
    state: restarted
  listen: "restart web services"
  
- name: restart httpd
  service:
    name: '{{ web_pkg }}'
    enabled: true
    state: started
  when: ansible_distribution == "RedHat" 
  listen: "restart web services"

- name: Restart Apache in node1
  service:
    name: '{{ web_pkg2 }}'
    state: restarted
    enabled: yes
  when: ansible_distribution == 'Ubuntu'
  listen: "restart web services"
